apiVersion: v1
kind: ConfigMap
metadata:
  name: test-saver
data:
  nats-url: {{ .Values.natsUrl }}
  finished-subject: 'test_suite.*.completed'
  database-url: 'postgresql://secureapi:secureapi@db-my-postgresql:5432/secureapi'
  rollbar-token: 'not_set'
