apiVersion: v1
kind: ConfigMap
metadata:
  name: test-saver
data:
  nats-url: {{ .Values.natsUrl }}
  finished-subject: 'test_suite.*.completed'
  database-url: {{ .Values.db.Url }}
  rollbar-token: 'not_set'
